### ISSUE TITLE
What is the license on the code?

### ISSUE THREAD

**Issue by pedro-delphina** [zahraatashgahi/QuickSelection#1]
Hello, I'd like to explore QuickSelection method for an application at work but the license of the code is unclear which might make using it challenging. Would it be possible to explicitly add a license? MIT license would be ideal and I see many repos with research on this area have that license as well. Thank you!

**Comment by zahraatashgahi** [comment]
Hello, thanks for bringing this up. I've updated the license of the project.

**Comment by pedro-delphina** [comment]
Thank you!
